[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#00FFAA"
backgroundColor = "#000000"
secondaryBackgroundColor = "#1C1C1C"
textColor = "#FFFFFF"
font = "sans serif"